# Generated by Django 5.1.3 on 2024-11-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohorario', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
