# Generated by Django 5.1.3 on 2024-12-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohorario', '0004_profissional_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
