# Generated by Django 5.1.3 on 2024-12-13 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autohorario', '0005_alter_profissional_endereco'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
