# Generated by Django 5.1.3 on 2025-01-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohorario', '0006_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='imagem',
            field=models.ImageField(blank=True, default='Imagem_do_WhatsApp_de_2023-08-27_às_20.55.51.jpg', null=True, upload_to='media/profile_pictures'),
        ),
    ]
