# Generated by Django 5.1.2 on 2025-02-03 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohorario', '0007_profissional_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='id_atividade',
            field=models.ManyToManyField(blank=True, to='autohorario.atividade'),
        ),
        migrations.CreateModel(
            name='VinculoProfissionalAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autohorario.atividade')),
                ('id_profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autohorario.profissional')),
            ],
            options={
                'unique_together': {('id_profissional', 'id_atividade')},
            },
        ),
    ]
