# Generated by Django 5.1.3 on 2025-02-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohorario', '0010_alter_profissional_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='oi'),
        ),
    ]
