# Generated by Django 5.1.3 on 2025-02-03 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autohorario', '0011_alter_profissional_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='dia_da_semana',
        ),
    ]
