# Generated by Django 5.1.3 on 2025-02-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohorario', '0012_remove_atividade_dia_da_semana'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vinculoprofissionalatividade',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='id_atividade',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='id_atividade',
        ),
        migrations.AddField(
            model_name='atividade',
            name='id_profissional',
            field=models.ManyToManyField(to='autohorario.profissional'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='id_turma',
            field=models.ManyToManyField(to='autohorario.turma'),
        ),
        migrations.AddField(
            model_name='vinculoprofissionalatividade',
            name='id_turma',
            field=models.ManyToManyField(to='autohorario.turma'),
        ),
        migrations.RemoveField(
            model_name='vinculoprofissionalatividade',
            name='id_profissional',
        ),
        migrations.AddField(
            model_name='vinculoprofissionalatividade',
            name='id_profissional',
            field=models.ManyToManyField(to='autohorario.profissional'),
        ),
    ]
