# Generated by Django 5.1.3 on 2025-02-13 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohorario', '0013_alter_vinculoprofissionalatividade_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='carga_horaria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='id_caracteristica',
            field=models.ForeignKey(blank=True, help_text='Geminar fará com que todos os períodos ocorram sequencialmente. Separar fará com que todos os períodos ocorram em momentos distintos.', null=True, on_delete=django.db.models.deletion.PROTECT, to='autohorario.caracteristica'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='periodos',
            field=models.SmallIntegerField(blank=True, help_text='Este campo será usado como referência para a quantidade de períodos semanal que esta atividade ocupará na agenda.', null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='qnt_de_alunos',
            field=models.IntegerField(blank=True, help_text='Usado apenas para ajudar na identificação ao criar as turmas', null=True),
        ),
    ]
