# Generated by Django 5.1.3 on 2025-02-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autohorario', '0014_alter_atividade_carga_horaria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='endereco',
        ),
    ]
