# Generated by Django 5.1.3 on 2025-02-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohorario', '0015_remove_profissional_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='funcao',
            field=models.CharField(blank=True, help_text='Usado apenas para ajudar na identificação dos profissionais', max_length=255, null=True),
        ),
    ]
